# Utiliser l'image de base officielle Playwright
FROM mcr.microsoft.com/playwright:v1.44.1

# Définir le répertoire de travail
WORKDIR /tests

# Copier les fichiers de projet
COPY . .

# Installer les dépendances
RUN npm install

# Exécuter les tests
CMD ["npx", "playwright", "test"]